### ISSUE TITLE
Compilation error, Ubuntu 22.04

### ISSUE THREAD

**Issue by amarcis** [ihmc3jn09hk/SMTPMail-drogon#8]
Fresh install, Ubuntu 22.04, (OpenSSL version 3.0.2) and Drogon - current version.
Compilation error:
-----
/home/dd/mbd/plugins/SMTPMail.cc: In function ‘void messagesHandle(const TcpConnectionPtr&, trantor::MsgBuffer*, const std::shared_ptr<EMail>&, const std::function<void(const std::__cxx11::basic_string<char>&)>&)’:
/home/dd/mbd/plugins/SMTPMail.cc:153:39: error: cannot convert ‘messagesHandle(const TcpConnectionPtr&, trantor::MsgBuffer*, const std::shared_ptr<EMail>&, const std::function<void(const std::__cxx11::basic_string<char>&)>&)::<lambda()>’ to ‘std::function<void(const std::shared_ptr<trantor::TcpConnection>&)>&&’
  153 |         connPtr->startClientEncryption(
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
  154 |             [connPtr, out]()
      |             ~~~~~~~~~~~~~~~~
  155 |             {
      |             ~
  156 |                 // LOG_TRACE << "SSL established";
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  157 |                 connPtr->send(out);
      |                 ~~~~~~~~~~~~~~~~~~~
  158 |             },
      |             ~~
  159 |             false,
      |             ~~~~~~
  160 |             false);
      |             ~~~~~~
In file included from /usr/local/include/trantor/net/TcpClient.h:22,
-----

**Comment by ihmc3jn09hk** [comment]
> ## Fresh install, Ubuntu 22.04, (OpenSSL version 3.0.2) and Drogon - current version.
> Compilation error:
> ## /home/dd/mbd/plugins/SMTPMail.cc: In function ‘void messagesHandle(const TcpConnectionPtr&, trantor::MsgBuffer*, const std::shared_ptr&, const std::function<void(const std::__cxx11::basic_string&)>&)’:
> /home/dd/mbd/plugins/SMTPMail.cc:153:39: error: cannot convert ‘messagesHandle(const TcpConnectionPtr&, trantor::MsgBuffer*, const std::shared_ptr&, const std::function<void(const std::__cxx11::basic_string&)>&)::<lambda()>’ to ‘std::function<void(const std::shared_ptrtrantor::TcpConnection&)>&&’
> 153 | connPtr->startClientEncryption(
> | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
> 154 | connPtr, out
> | ~~~~~~~~~~~~~~~~
> 155 | {
> | ~
> 156 | // LOG_TRACE << "SSL established";
> | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 157 | connPtr->send(out);
> | ~~~~~~~~~~~~~~~~~~~
> 158 | },
> | ~~
> 159 | false,
> | ~~~~~~
> 160 | false);
> | ~~~~~~
> In file included from /usr/local/include/trantor/net/TcpClient.h:22,

Thank you for reporting.

Fixed by #7

**Comment by amarcis** [comment]
Thank you very much. It works!
